core/urls.py
from django.conf.urls import url

from . import views
from core.views import *


app_name = "core"
urlpatterns = [
    url(r'^$', views.GroupListView.as_view(), name="list"),
    url(r'^git_users/$', views.GitUserListView.as_view(), name="u_list"),
    url(r'^users_data/(?P<pk>\d+)/$', views.DataListView.as_view(), name="data_list"),
    url(r'^user_data/(?P<id>\d+)/$', views.UserDataListView.as_view(), name='user_data'),
    url(r'^add_group/$', views.CreateGroupView.as_view(), name="add"),
    url(r'^edit_group/(?P<pk>\d+)/$', views.UpdateGroupView.as_view(), name="group"),
    url(r'^edit_git_user/(?P<pk>\d+)/$', views.UpdateGitUserView.as_view(), name="git_user"),
    url(r'^edit_group/(?P<pk>\d+)/add-user/$', views.AddUserView.as_view(), name="add_user"),

    url(r'^delete_group/(?P<id>\d+)/$', delete_group, name='delete_group'),
    url(r'^edit_group/delete_user/(?P<id>\d+)/(?P<pk>\d+)/$', delete_user, name='delete_user'),
    url(r'^git_users/delete_git_user/(?P<id>\d+)/$', delete_git_user, name='delete_git_user'),
    # url(r'^add_git_user/$', views.CreateGitUserView.as_view(), name="add_git"),
]

gitleague/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import core.views

# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    url(r'', include('core.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', core.views.LoginView.as_view(), name='login'),
    url(r'^logout/$', core.views.LogoutView.as_view(), name='logout'),
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib import auth
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext as _


class GitUser(models.Model):
    user = models.ManyToManyField(auth.models.User,
                              related_name='user',
                              verbose_name=_("user"))
    username = models.CharField(_('username'), max_length=40)
    email = models.EmailField(_('EMail'), null=True, blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("core:git_user", args=[str(self.pk)])


class Group(models.Model):
    owner = models.ForeignKey(auth.models.User,
                             related_name='owener',
                             verbose_name=_("owener"))
    name = models.CharField(_('name'), max_length=40)
    created_at = models.DateField(_('created_at'))
    git_users = models.ManyToManyField(GitUser, blank=True, related_name='groups')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:group", args=[str(self.pk)])


class Data(models.Model):
    gitUser = models.ForeignKey(GitUser)
    created_at = models.DateField(_('created_at'))
    event_type = models.CharField(_('event_type'), max_length=30)
    repository = models.CharField(_('repository'), max_length=70)
    description = models.TextField(_('description'), null=True, blank=True)

    def __str__(self):
        return "User: {}, created at: {}. Event: {}".format(
            self.gitUser, self.created_at, self.event_type)

core/forms.py
from django import forms
from core.models import GitUser, Group


class LoginForm(forms.Form):
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())


class GitUserForm(forms.ModelForm):

    class Meta:
        model = GitUser
        fields = ['email']

    email = forms.EmailField()


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ['name']

    name = forms.CharField(max_length=40)

core/views.py
import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.http.response import HttpResponseRedirect, HttpResponse, JsonResponse, Http404
from django.shortcuts import redirect, render, get_object_or_404, get_list_or_404
from django.utils.encoding import escape_uri_path
from django.views.generic import View
from django.views.generic.edit import FormView, UpdateView
from django.views.generic.list import ListView
from core.forms import *
from core.github_content import *
from core.models import *


class LoginView(FormView):
    form_class = LoginForm
    template_name = "login.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('core:list')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

        if user is not None and user.is_active:
            login(self.request, user)
            if self.request.GET.get('from'):
                return redirect(self.request.GET['from'])  # SECURITY: check path
            return redirect('core:list')

        form.add_error(None, "Invalid user name or password")
        return self.form_invalid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("login")


class LoggedInMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            url = reverse("login") + "?from=" + escape_uri_path(request.path)
            return redirect(url)
        return super().dispatch(request, *args, **kwargs)


class GroupListView(LoggedInMixin, ListView):
    page_title = 'groups list'
    model = Group

    def get_context_data(self, **kwargs):
        context = super(GroupListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class CreateGroupView(LoggedInMixin, FormView):
    page_title = 'create group'
    form_class = GroupForm
    template_name = "core/group_form.html"
    success_url = reverse_lazy('core:list')

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.created_at = datetime.datetime.now()
        form.save()
        return super().form_valid(form)


class UpdateGroupView(LoggedInMixin, UpdateView):
    form_class = GroupForm
    model = Group
    template_name = "core/group_edit.html"
    success_url = reverse_lazy('core:list')

    def page_title(self):
        return self.object.name

    def get_object(self, queryset=None):
        return Group.objects.get(id=self.kwargs['pk'])

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Group: {}, has been updated'.format(form.instance.name))
        return redirect('core:list')


class UpdateGitUserView(LoggedInMixin, UpdateView):
    form_class = GitUserForm
    model = GitUser
    template_name = 'core/git_user_edit.html'
    success_url = reverse_lazy('core:u_list')

    def page_title(self):
        return "Edit {}".format(self.object.username)

    def get_initial(self):
        return super().get_initial()

    def get_object(self, queryset=None):
        return GitUser.objects.get(id=self.kwargs['pk'])

    def form_valid(self, form):
        form.save()
        return redirect('core:list')


class GitUserListView(LoggedInMixin, ListView):
    page_title = 'Git users list'
    model = GitUser

    def get_context_data(self, **kwargs):
        context = super(GitUserListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class DataListView(LoggedInMixin, ListView):
    page_title = 'Data list'
    model = Data

    def get_object(self):
        return get_object_or_404(Group, id=self.kwargs['pk'])
        # return Group.objects.get(id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(DataListView, self).get_context_data(**kwargs)
        q = self.request.GET.get("browse")
        context['input'] = q
        return context

    def get_queryset(self):
        if not get_object_or_404(Group, pk=self.kwargs['pk']).git_users:
            return redirect('core:list')

        users_data_list = last_50(id=self.kwargs['pk'])[:50]
        if self.request.GET.get("browse"):
            selection = self.request.GET.get("browse")
            if selection == "1":
                users_data_list = last_50(id=self.kwargs['pk'])
                return users_data_list[:50]
            elif selection == "2":
                users_data_list = last_5_commits(id=self.kwargs['pk'])
                return users_data_list
            elif selection == "3":
                users_data_list = top_commit_user(self.kwargs['pk'])
                return users_data_list
            elif selection == "4":
                return users_data_list[:4]
        return users_data_list


def delete_group(request, id):
    Group.objects.get(pk=id).delete()
    messages.success(request, 'The group was deleted successfully')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def delete_git_user(request, id):
    delete_user_data(GitUser.objects.get(pk=id).username)
    GitUser.objects.get(pk=id).delete()
    messages.success(request, 'The github user was deleted successfully')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def delete_user(request, id, pk):
    group = get_object_or_404(Group, pk=pk)
    user = GitUser.objects.filter(id=id).first()
    user.groups.remove(group)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def last_50(id):
    users_data_list = Data.objects.filter(
        gitUser=get_object_or_404(Group, id=id).git_users.all()[0])

    for t in get_object_or_404(Group, id=id).git_users.all():
        users_data_list |= Data.objects.filter(gitUser=t)

    users_data_list = users_data_list.order_by('-created_at')
    users_data_list = users_data_list

    return users_data_list


def last_5_commits(id):
    users_data_list = Data.objects.filter(
        gitUser=Group.objects.get(id=id).git_users.all()[0])[:5]
    return users_data_list


def top_commit_user(id):
    q1 = '''
    SELECT id, gitUser_id, created_at, COUNT(description) as 'commits' FROM core_data GROUP BY gitUser_id, created_at
    '''
    q = """
    SELECT core_data.id, core_data.gitUser_id, core_data.created_at, COUNT(description) as 'commits'
    FROM core_data, core_group_git_users
    WHERE core_group_git_users.group_id={} and
          core_group_git_users.gituser_id=core_data.gitUser_id
    GROUP BY core_data.gitUser_id, created_at
    """.format(id)
    q2 = '''
    SELECT * FROM core_data
    '''
    users_data_list = Data.objects.raw(q)
    # con = sqlite3.connect('Django default')
    # cur = con.cursor()
    #
    # cur.execute(q)
    # row = cur.fetchone()
    return users_data_list


class UserDataListView(LoggedInMixin, ListView):
    page_title = 'Data list'
    model = Data

    def get_queryset(self):
        u = get_object_or_404(GitUser, pk=self.kwargs['id'])
        users_data_list = Data.objects.filter(gitUser=u).all()

        if not users_data_list:
            raise Http404("User has no commits activity.")

        return users_data_list


class AddUserView(LoggedInMixin, View):
    def post(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=kwargs['pk'])
        user_name = request.POST.get('username')

        user = GitUser.objects.filter(username=user_name).first()

        if user is None:

            if not is_git_user(user_name):
                return JsonResponse(
                    {
                        'message': 'There is no github user with username "{}". Sorry, try again'.format(user_name),
                    },
                    status=400,
                )
            add_user_data(user_name)
            user = GitUser.objects.filter(username=user_name).first()

        user.user.add(self.request.user)
        if not user.groups.filter(id=group.id).exists():
            user.groups.add(group)
        else:
            return render(request, "")
        return render(request, "core/_user.html", {
            'u': user,
            'object': group,
        })


# class CreateGitUserView(LoggedInMixin, FormView):
#     page_title = 'Add user'
#     form_class = GitUserForm
#     template_name = "core/git_form.html"
#     success_url = reverse_lazy('core:u_list')
#
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)
#
#     def form_valid(self, form):
#         user_name = form.instance.username
#         exist = GitUser.objects.filter(username=user_name)
#         if exist:
#             # if self.request.user in exist[0].user:
#             messages.error(self.request,
#                            'The github user "{}" is already in database. Please add another github user.'.format(
#                                user_name))
#             return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
#
#         if is_git_user(user_name):
#             form.save()
#             i = add_user_data(user_name)
#             gu = GitUser.objects.filter(username=user_name)
#             gu.email = i[1]
#             gu.user.add(self.request.user)
#             messages.success(self.request, 'A new git user has been recorded with {} commits'.format(i[0]))
#         else:
#             messages.error(self.request,

core/templates/core/_user.html
{% load humanize %}

<tr>
    <td style="width: 150px;">
         <b>
            <a href='/user_data/{{ u.id }}'>{{ u }}</a>
        </b>
    </td>
    <td style="width: 250px;">
        <strong>Email:</strong> <a href="/edit_git_user/{{ u.id }}">{{ u.email }}</a>
    </td>
    <td>
        <a href='/edit_group/delete_user/{{ u.id }}/{{ object.pk }}'>Remove</a>
    </td>
</tr>

core/templates/core/data_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
        <form method="GET">
            <select name="browse">
                <option value="1">last 50 goup commits</option>
                <option value="2">last 5 commits a user- not working</option>
                <option value="3">top commit user</option>
            </select>

<input type="submit" value="Submit" />

</form>
    {% if object_list.count %}
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>User name</th>
                    <th style="width: 110px">Created at</th>
                    <th>repository</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>
                            <a href='/user_data/{{ object.gitUser.id }}'>
                                {{ object.gitUser }}
                            </a>
                        </td>
                        <td>{{ object.created_at }}</td>
                        <td>{{ object.repository }}</td>
                        <td>{{ object.description }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        No data.... yet!
    {% endif %}
{% endblock %}

core/templates/core/git_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

    <a href="{% url "core:list" %}">Users</a>
    &gt;
    Add new user...

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

core/templates/core/git_user_edit.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

    <a href="{% url "core:u_list" %}">Git users</a>
    &gt;
    Edit a git user...

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Update user data
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

core/templates/core/gituser_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    {% if object_list.count %}
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>User email</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>
                            <a href="{{ object.get_absolute_url }}">
                                {{ object.username }}
                            </a>
                        </td>
                        <td>{{ object.email }}</td>
                        <td><a href='delete_git_user/{{ object.id }}'>Delete</a></td>
                        <td><a href='/user_data/{{ object.id }}'>Commits</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        No git users.... yet!
    {% endif %}
{% endblock %}

core/templates/core/group_edit.html
{% extends "base.html" %}
{% load bootstrap3 staticfiles %}

{% block content %}

    <a href="{% url 'core:list' %}">Groups</a>
    &gt;
    Edit group...    <a href='/users_data/{{ object.id }}'>View group's commits</a>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        {% endbuttons %}
    </form>
    <table class="table table-bordered table-striped">
        <tbody id="users">
                {% for u in object.git_users.all %}
                    {% include "core/_user.html" %}
                {% endfor %}
            <tr id="xx"></tr>
        </tbody>
    </table>
    <form method="post" id="userform" action="{% url 'core:add_user' object.id %}">
        {% csrf_token %}
        <input type="text" id="id_username" name="username">
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Add
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'csrf.js' %}"></script>
    <script src="{% static 'group_detail.js' %}"></script>
{% endblock %}

core/templates/core/group_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

    <a href="{% url "core:list" %}">Groups</a>
    &gt;
    Add new group...

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        {% endbuttons %}
    </form>


{% endblock %}

core/templates/core/group_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    {% if object_list.count %}
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Group name</th>
                    <th>Created</th>
                    <th>Members</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>
                            <a href="users_data/{{ object.id }}">
                                {{ object.name }}
                            </a>
                        </td>
                        <td>{{ object.created_at }}</td>
                        <td>{{ object.git_users.count }}</td>
                        <td>
                            <a href='delete_group/{{ object.id }}'>Delete</a>,
                            <a href='{{ object.get_absolute_url }}'>Edit</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        No groups.... yet!
    {% endif %}
    <a href="{% url "core:add" %}">+ Add new group</a>
{% endblock %}